# Generated by SUB Native Compiler
# Architecture: x86-64

.section .rodata
.LC0:
    .string "%ld\n"
.section .data
.section .text
.global main

main:
    # Function prologue
    pushq %rbp
    movq %rsp, %rbp
    movq $0, %rax
    jmp main_return
    # Function epilogue
main_return:
    movq %rbp, %rsp
    popq %rbp
    ret


# Exit
.section .note.GNU-stack,"",@progbits
